<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="league" nsURI="league" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="League">
    <eStructuralFeatures xsi:type="ecore:EReference" name="club" upperBound="-1" eType="#//Team"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Team">
    <eStructuralFeatures xsi:type="ecore:EReference" name="manager" lowerBound="1"
        eType="#//Manager" containment="true" eOpposite="#//Manager/coach"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" upperBound="-1"
        eType="#//Player" containment="true" eOpposite="#//Player/squadMember"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Member">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Manager" eSuperTypes="#//Member">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coach" lowerBound="1" eType="#//Team"
        eOpposite="#//Team/manager"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player" eSuperTypes="#//Member">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="#//Position"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="squadMember" lowerBound="1"
        eType="#//Team" eOpposite="#//Team/player"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Position">
    <eLiterals name="forward"/>
    <eLiterals name="defender" value="1"/>
    <eLiterals name="goalkeeper" value="2"/>
  </eClassifiers>
</ecore:EPackage>
